version: "3.9" # optional since v1.27.0
services:

  # postgresql:
  #   build:
  #     context: ./postgresql
  #   restart: unless-stopped
  #   volumes:
  #     - postgresql-data:/var/lib/postgresql/data
  #   env_file: 
  #     - postgresql/postgresql.env
  #   ports:
  #     - 5432:5432
  #   # networks:
  #   #   - backend

  signaling_server:
    container_name: signaling
    build:
      context: .
      dockerfile: signaling/Dockerfile
    ports: 
      - 5000:5000
      - 5001:5001

  ms_mirror1:
    container_name: ms_mirror1
    build:
      context: .
      dockerfile: kurento/Dockerfile
    environment: 
      - MS_ROLE=mirror
      - SIGNALING_SERVER=host.docker.internal:5000
      - KMS_MIN_PORT=6001
      - KMS_MAX_PORT=6010
      - GST_DEBUG="2,Kurento*:3,kms*:3,sdp*:3,webrtc*:3,*rtpendpoint:3,rtp*handler:3,rtpsynchronizer:3,agnosticbin:3"
    ports: 
      - 8001:5001
      - 8888:8888
      - 6001-6010:6001-6010/udp

  ms_mirror2:
    container_name: ms_mirror2
    build:
      context: .
      dockerfile: kurento/Dockerfile
    environment: 
      - MS_ROLE=mirror
      - SIGNALING_SERVER=host.docker.internal:5000
      - KMS_MIN_PORT=6011
      - KMS_MAX_PORT=6020
      - GST_DEBUG="2,Kurento*:2,kms*:2,sdp*:2,webrtc*:2,*rtpendpoint:2,rtp*handler:2,rtpsynchronizer:2,agnosticbin:2"
    ports: 
      - 8002:5001
      - 8889:8888
      - 6011-6020:6011-6020/udp

  ms_mirror3:
    container_name: ms_mirror3
    build:
      context: .
      dockerfile: kurento/Dockerfile
    environment: 
      - MS_ROLE=mirror
      - SIGNALING_SERVER=host.docker.internal:5000
      - KMS_MIN_PORT=6021
      - KMS_MAX_PORT=6030
      - GST_DEBUG="2,Kurento*:2,kms*:2,sdp*:2,webrtc*:2,*rtpendpoint:2,rtp*handler:2,rtpsynchronizer:2,agnosticbin:2"
    ports: 
      - 8003:5001
      - 8890:8888
      - 6021-6030:6021-6030/udp

  ms_recorder1:
    container_name: ms_recorder1
    build:
      context: .
      dockerfile: kurento/Dockerfile
    environment: 
      - MS_ROLE=recorder
      - SIGNALING_SERVER=host.docker.internal:5000
      - AWS_BUCKET_NAME=tdx-recordings
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_KEY=secret
      - KMS_MIN_PORT=6031
      - KMS_MAX_PORT=6040
      - GST_DEBUG="2,Kurento*:2,kms*:2,sdp*:2,webrtc*:2,*rtpendpoint:2,rtp*handler:2,rtpsynchronizer:2,agnosticbin:2"
    ports: 
      - 9001:5001
      - 8891:8888
      - 6031-6040:6031-6040/udp

  ms_recorder2:
    container_name: ms_recorder2
    build:
      context: .
      dockerfile: kurento/Dockerfile
    environment: 
      - MS_ROLE=recorder
      - SIGNALING_SERVER=host.docker.internal:5000
      - AWS_BUCKET_NAME=tdx-recordings
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_KEY=secret
      - KMS_MIN_PORT=6041
      - KMS_MAX_PORT=6050
      - GST_DEBUG="2,Kurento*:2,kms*:2,sdp*:2,webrtc*:2,*rtpendpoint:2,rtp*handler:2,rtpsynchronizer:2,agnosticbin:2"
    ports: 
      - 9002:5001
      - 8892:8888
      - 6041-6050:6041-6050/udp

#   turn:
#     container_name: coturn
#     image: coturn/coturn
#     restart: always
#     volumes:
#       - ${PWD}/coturn/turnserver.conf:/etc/turnserver.conf
#       - ${PWD}/coturn/privkey.pem:/etc/ssl/private/privkey.pem
#       - ${PWD}/coturn/cert.pem:/etc/ssl/certs/cert.pem
#     ports:
# ## STUN/TURN
#       - "3478:3478"
#       - "3478:3478/udp"
#       - "3479:3479"
#       - "3479:3479/udp"
#       - "80:80"
#       - "80:80/udp"
# ## STUN/TURN SSL
#       - "5349:5349"
#       - "5349:5349/udp"
#       - "5350:5350"
#       - "5350:5350/udp"
#       - "443:443"
#       - "443:443/udp"
# # Relay Ports
#       - "49500-50000:49500-50000"
#       - "49500-50000:49500-50000/udp"
#     # networks:
#     #   - frontend
#     #   - backend
#     depends_on:
#       - postgresql
#     env_file:
#       - coturn/coturn.env
# # DB
#       - postgresql/postgresql.env
# volumes:
#   postgresql-data:

# # networks:
# #   frontend:
# #     driver: bridge
# #     ipam:
# #       driver: default
# #       config:
# #         - subnet: 172.16.238.0/24
# #   backend:
# #     internal: true
